name: ci using conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-linux:
    runs-on: ubuntu-latest
    build_type: "Release", cc: "gcc", cxx: "g++"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Install module
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pytest tests
    
